---
repos:
  - repo: local
    hooks:
      - id: poe-format
        name: poe-format
        language: system
        pass_filenames: false
        entry: poetry
        args:
          - run
          - poe
          - format
      - id: poe-lint
        name: poe-lint
        language: system
        pass_filenames: false
        entry: poetry
        args:
          - run
          - poe
          - lint
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.16.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=.md
      - id: check-added-large-files
        args:
          - --maxkb=512
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args:
          - --autofix
      - id: mixed-line-ending
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: shellcheck
        exclude: .*\.sh\.j2
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint-system
